### PR TITLE
fixed search landing page issue(#927)

### LINKED ISSUE #927: search showing home page first

### PR DESCRIPTION
**Pull request by gyanpgupta**
/kind ui-change
Fixes #927

### CODE REVIEW

**Comment by gyanpgupta** [comment]
@puncsky , please have a look, the issue was when we add /?search=url to URL it was showing the home page first then redirecting to the main page so I fixed it.

File: src/shared/home/home.tsx [hunk 1]
```diff
@@ -18,22 +20,43 @@ type State = {
...
 };
 
-type Props = RouteComponentProps<PathParamsType> & {};
+type Props = RouteComponentProps<PathParamsType> & WithApolloClient<{}> & {};
 
 class HomeComponent extends Component<Props, State> {
-  public state: State = {
-    marketCap: 0,
-    price: 0,
-    name: "IOSG"
```
Comment (guo) [inline src/shared/home/home.tsx]: why IOSG is here?

File: src/shared/common/search-handler.tsx [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+};
+
+export const handleSearch = async (
+  props: Props,
+  query: string
+): Promise<void> => {
+  const { history, client } = props;
+  const value = query.trim();
+
+  if (value.startsWith("io")) {
```
Comment (nmhung1210) [inline src/shared/common/search-handler.tsx]: You can use the regular expression as below for more accuracy:
```suggestion
  if (value.match(/^io[a-z0-9]{39}/)) {
```

File: src/shared/common/search-handler.tsx [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+    return history.push(`/address/${value}`);
+  }
+  if (value.length === 130) {
```
Comment (nmhung1210) [inline src/shared/common/search-handler.tsx]:
```suggestion
  if (value.match(/^[a-z0-9]{130}$/)) {
```

File: src/shared/home/home.tsx [hunk 4]
```diff
@@ -18,22 +20,43 @@ type State = {
...
-  };
+  constructor(props: Props) {
+    super(props);
+    const urlParams = new URLSearchParams(props.history.location.search);
+    this.state = {
+      marketCap: 0,
+      price: 0,
+      name: "IOSG",
```
Comment (nmhung1210) [inline src/shared/home/home.tsx]: The `name` was wrong and not used. Pls. remove it.

**Comment by gyanpgupta** [comment]
@nmhung1210 , @puncsky , updated , please have a look. thanks

File: src/shared/home/home.tsx [hunk 5]
```diff
@@ -20,23 +22,42 @@ import { StatsArea } from "./stats-area";
...
+    this.state = {
+      marketCap: 0,
+      price: 0,
+      search: urlParams.get("search") || ""
+    };
+  }
+
+  public componentDidMount(): void {
+    if (this.state.search) {
+      handleSearch(
```
Comment (nmhung1210) [inline src/shared/home/home.tsx]: We need the home page to be shown first. So please `setTimeout` for the `handleSearch` around 2s to avoid redirecting immediately to search target page.
