### PR TITLE
Fixed #891: Stats bugs

### LINKED ISSUE #891: stats bugs
image

1. The TPS is a float number
2. Productivity calculation is wrong. Hide the graph before we figure out the right way to calculate it
3. Number of consensus delegate is wrong. It is supposed to be 24, we need to review the implementation

### PR DESCRIPTION
**Pull request by nmhung1210**
**What type of PR is this?**
bug

**What this PR does / why we need it**:

This PR is to fix consensus delegate/candidates count. (Part 2 of the issue)

**Which issue(s) this PR fixes**:

Fixes #891 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: src/shared/home/stats/candidates-card.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ export const CandidatesCard = (): JSX.Element => {
           a => a.category === "CONSENSUS_DELEGATE"
         ).length;
         const candidatesCount = bpCandidates.filter(
-          a => a.category === "DELEGATE_CANDIDATE"
+          a => a.category !== "CONSENSUS_DELEGATE"
```
Comment (CoderZhi) [inline src/shared/home/stats/candidates-card.tsx]: consensus delegates are also candidates. For now, we have three different roles:
1. DELEGATE_CANDIDATE, who are not delegate yet
2. DELEGATE, who are delegate, not consensus delegate yet
3. CONSENSUS_DELEGATE, who are DELEGATE as well and may or may not participate in consensus
4. CONSENSUS_DELEGATE with productivityBase > 0, who are CONSENSUS_DELEGATE and is actively participate in consensus now.

Comment (nmhung1210) [reply src/shared/home/stats/candidates-card.tsx]: Thank you for your explanation. I just pushed commits to fix it.
