### PR TITLE
fixed pending tx page title

### LINKED ISSUE #854: Pending tx page has a weird tittle
Screen Shot 2019-07-12 at 11 16 31 AM

Repro: when tx is not finalized on chain or does not exist (e.g., https://www.iotexscan.io/action/159f8f34f49f3c51f20bae1cf707971befbe1c7825d18ab5fa37064f51ebec11),
Suggested fix: replace "- Brand" with "IoTeX Pending Action 15...c10"

### PR DESCRIPTION
**Pull request by gyanpgupta**
/kind ui-change

Fixes #854

### CODE REVIEW

File: src/shared/common/action-not-found.tsx [hunk 1]
```diff
@@ -13,30 +13,33 @@ import { ContentPadding } from "../common/styles/style-padding";
...
-}
+type Props = {
+  info?: string;
+};
+
+export const ActionNotFound = ({ info }: Props): JSX.Element => (
+  <>
+    <Helmet title={`${t("action.notFound")} - IoTeX`} />
+    <ContentPadding>
+      <Navigation />
```
Comment (nmhung1210) [inline src/shared/common/action-not-found.tsx]: We don't need to show breadcrumb, PageTitle, Overview for a not found action.
image

File: src/shared/common/action-not-found.tsx [hunk 2]
```diff
@@ -1,42 +1,21 @@
...
-      </ContentPadding>
-    </>
-  );
-}
+type Props = {
+  info?: string;
+};
+
+export const ActionNotFound = ({ info }: Props): JSX.Element => (
+  <ErrorPage
```
Comment (nmhung1210) [inline src/shared/common/action-not-found.tsx]: We still need to keep `<Helmet title={`${t("action.notFound")} - IoTeX`} />` here.

**Comment by puncsky** [comment]
i think we can make this polling as well.

**Comment by gyanpgupta** [comment]
@puncsky  Added polling at interval of 6 secs. please have a look thanks

File: src/shared/action/action-detail.tsx [hunk 3]
```diff
@@ -188,6 +190,9 @@ class ActionDetailsInner extends PureComponent<Props> {
               this.setState({ loading });
               if (error) {
                 this.setState({ error: true });
+                setTimeout(() => {
+                  this.setState({ error: false });
```
Comment (nmhung1210) [inline src/shared/action/action-detail.tsx]: why the `error` false here? It will make the screen flash.

Comment (gyanpgupta) [reply src/shared/action/action-detail.tsx]: @nmhung1210  fixed. please have a look

**Comment by puncsky** [comment]
please update

File: src/shared/action/action-detail.tsx [hunk 4]
```diff
@@ -153,16 +153,18 @@ class ActionDetailsInner extends PureComponent<Props> {
...
     const {
       match: {
         params: { hash }
       },
       showContentPadding = true,
       showNavigation = true
     } = this.props;
+    const POLL_INTERVAL = 6000;
+
+    if (this.state.error) {
```
Comment (nmhung1210) [inline src/shared/action/action-detail.tsx]: This will unmount the `Query` tag below it and stop the polling as well. You can simplify this by checking the `error` at the Query response and the return `ActionNotFound` there.

**Comment by gyanpgupta** [comment]
@nmhung1210 , @puncsky  updated, please have a look thanks
