### PR TITLE
Fix staked

### LINKED ISSUE #1356: Display total supply, total circulating supply and update Staked IOTX in the dashboard
For Total supply and total circulating supply, use below

http://analytics.iotexscan.io/
```
query{
	chain {
    totalSupply
    totalCirculatingSupply,
  }
}
```

For "Staked IOTX", it should be calculated using "totalCirculatingSupply" from the above query, not the fixed 5,400,000,000.

Screen Shot 2020-06-19 at 4 36 11 PM

### PR DESCRIPTION
**Pull request by hunglmtb**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind backend-change
> /kind ui-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1356

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: src/shared/home/stats/staked-card.tsx [hunk 1]
```diff
@@ -27,14 +25,17 @@ export const StakedVotesCard = (): JSX.Element => {
...
+          totalSupply: number;
+          totalCirculatingSupply: number;
+        } = (data && data.chain) || {};
 
-        const percent = Number(
-          ((totalVotedStakes / CIRCULATING_SUPPLY) * 100).toFixed(2)
-        );
+        const percent =
+          totalSupply > 0
+            ? Number(((totalCirculatingSupply / totalSupply) * 100).toFixed(2))
```
Comment (guo) [inline src/shared/home/stats/staked-card.tsx:37]: voted token / total circulating supply
