### PR TITLE
wrapped logs data to fix size

### LINKED ISSUE #867: fold "Data" and "Logs" fields
If "Data" is more than line (very long), fold the field in some way:
1. Add a show more button:
    Data: 6014379871047198042390980... Show More
2. Or, show in a textbox with fix size.

Do the same thing for field "Logs".

Example:
https://testnet.iotexscan.io/action/99b120d1abbafc4f46bebd81803ca325da2fdfc168a4486b4a83bb11ed4fa589

### PR DESCRIPTION
**Pull request by gyanpgupta**
/kind ui-change
Fixes #867

### CODE REVIEW

File: src/shared/action/action-detail.tsx [hunk 1]
```diff
@@ -42,17 +42,17 @@ type Props = RouteComponentProps<PathParamsType> & {
...
-    if (typeof object[key] === "object" && !object[key].seconds) {
-      return {
-        key,
-        // @ts-ignore
-        value: <pre>{JSON.stringify(object[key], null, 2)}</pre>
-      };
+    let value = object[key];
+    if (typeof value === "object" && !value.seconds) {
+      value = (
+        <pre style={{ whiteSpace: "pre-wrap" }}>
```
Comment (nmhung1210) [inline src/shared/action/action-detail.tsx]: This just not works. You might need to use `textarea` (readonly) instead of `pre`.

**Comment by gyanpgupta** [comment]
data-screenshot
data-log-screenshot


this is how data looks in logs and only data. and with the text area it looks the same. should I change it. @nmhung1210

**Comment by nmhung1210** [comment]
> data-screenshot
> data-log-screenshot
> 
> this is how data looks in logs and only data. and with the text area it looks the same. should I change it. @nmhung1210

It looks good to me! Thanks
