### PR TITLE
change pagination order

### LINKED ISSUE #338: all paginations have wrong orders
Screen Shot 2019-04-19 at 11 13 42 PM

now it is from earliest to latest. it should be latest to earliest.

### PR DESCRIPTION
**Pull request by anshuomomo**
**What type of PR is this?**

> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #338 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: src/api-gateway/resolvers/antenna.ts [hunk 1]
```diff
@@ -88,7 +88,17 @@ export class AntennaResolver implements ResolverInterface<() => ChainMeta> {
     @Ctx()
     { gateways }: ICtx
   ): Promise<GetActionsResponse> {
-    return gateways.antenna.getActions(input);
+    if (input.byIndex) {
```
Comment (puncsky) [inline src/api-gateway/resolvers/antenna.ts]: do not change the default behavior of getActions / antenna resolvers.

just query on the client-side.
